### ISSUE TITLE
Use marisa-trie Python wrapper

### ISSUE THREAD

**Issue by pettarin** [pettarin/penelope#2]
Using the Python wrapper might help users: https://github.com/kmike/marisa-trie

**Comment by gk2go** [comment]
What's the point? Faster compilation? I wouldn't bother, and focus more on better output delivery, like mobi format. :)

**Comment by pettarin** [comment]
Now the user must installs MARISA via e.g. apt-get or other packet managers, or download its source code and compile it. Then, she has to modify the path in `penelope.py`.

The point of using the MARISA Python interface (instead of calling MARISA via subprocess) is to get (slightly) faster execution and, more importantly, a simpler, `pip`-based setup.

Clearly, if `penelope` itself was available through PyPI, `marisa-trie` would be a dependency, and it could be auto-installed by an hypothetical `pip install penelope`.

**Comment by pettarin** [comment]
Done in v3.0.0
