### ISSUE TITLE
Add support for MOBI/PRC dictionaries

### ISSUE THREAD

**Issue by pettarin** [pettarin/penelope#5]

**Comment by pettarin** [comment]
1) MOBI spec evolved over time, from the original Mobipocket spec to the current Kindle spec. This means possibly having to deal with slightly different syntaxes. Plus, the current Kindle is way more complex (= more tags etc.) than Stardict/Kobo/Bookeen formats. But perhaps you can simply start by supporting the features/tags you actually need.

Some links that I have noted down:

https://www.mobipocket.com/dev/article.asp?BaseFolder=prcgen&File=indexing.htm

http://www.mobileread.com/forums/showthread.php?t=20480

http://www.mobileread.com/forums/showthread.php?t=20994

http://www.mobileread.com/forums/showthread.php?t=90403

http://goldendict.org/forum/viewtopic.php?f=5&t=1319

https://github.com/Tvangeste/dsl2mobi

2) You will probably need to pack and unpack the MOBI files using kindlegen (not sure if it can pack MOBI _dictionaries_) and mobiunpack.py, respectively. I have not investigated this aspect.

**Comment by gk2go** [comment]
Ciao Pettarin, I think this would be very useful. How long do you estimate it would take to get this done and released?

**Comment by pettarin** [comment]
Unfortunately, I no longer have time to develop or maintain Penelope: https://github.com/pettarin/penelope#important-updates

**Comment by pettarin** [comment]
Added support to output MOBI dictionaries in v3.0.0.

**Comment by pettarin** [comment]
Better options in v3.1.0.

Closing this issue as reading from MOBI/PRC is not likely to happen anytime soon.
